// This file was auto-generated by ML.NET Model Builder. 

using Microsoft.ML.Data;

namespace WebAPIML.Model
{
    public class ModelInput
    {
        [ColumnName("Bedrooms"), LoadColumn(0)]
        public float Bedrooms { get; set; }


        [ColumnName("Bathrooms"), LoadColumn(1)]
        public float Bathrooms { get; set; }


        [ColumnName("Price"), LoadColumn(2)]
        public float Price { get; set; }


    }
}
